security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt
            cost: 12

    providers:
        amm_db:
            entity:
                class: App\Entity\User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~

            form_login:
                login_path: login
                check_path: login

            logout:
                path: /logout
                target: /

    access_control:
        -
            path: ^/admin
            roles: ROLE_ADMIN
