security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt
            cost: 12

    providers:
        amm_db:
            entity:
                class: App\Entity\User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~

            guard:
                authenticators:
                    - app.security.form_authenticator

            logout:
                path: /logout
                target: /

    access_control:
        -
            path: ^/admin
            roles: ROLE_ADMIN
