# Coding Style

cs:
    ./vendor/bin/php-cs-fixer fix --config=./.php_cs --dry-run --stop-on-violation --diff

cs-fix:
    ./vendor/bin/php-cs-fixer fix --config=./.php_cs

cs-ci:
    ./vendor/bin/php-cs-fixer fix --config=./.php_cs --dry-run --using-cache=no --verbose